name: Check Dependencies for New Release
on:
  pull_request:
    branches: master

# cron job

env:
  depend-cache: /home/runner/work/pepsirf-q2-plugin-docs/pepsirf-q2-plugin-docs/depend-cache

jobs:
  check-pepsirf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: LadnerLab/PepSIRF
          ref: master
          path: pepsirf
      - uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: 3.16.3

      - name: Cache pepsirf
        id: cache-pepsirf
        uses: actions/cache@v3
        with:
          path: ${{ env.depend-cache }}
          key: ${{ runner.os }}-pepsirf

      - name: Install pepsirf
        if: steps.cache-pepsirf.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/pepsirf
        shell: bash -l {0}
        run: |
          sudo apt update
          sudo apt install zlib1g
          sudo apt install -y libboost-all-dev
          mkdir build
          cd build
          cmake --version
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make pepsirf
          mkdir ${{ env.depend-cache }}
